/**
 * Every image on the site. Optimised copies live in /public/images/opt and are
 * generated by `python scripts/prepare-images.py` (watermark crop, warm-ivory
 * grade, WebP). An array is a fallback chain: the first file that loads wins.
 */
const opt = (name: string) => `/images/opt/${name}.webp`;

export type ImageSource = string | string[];

export const IMG = {
  hero: opt("hero"),
  coupleMain: opt("couple-main"),
  kiss: opt("kiss"),
  casual: [opt("casual"), "/images/opt/casual.jpeg"],
  foreheadKiss: [opt("forehead-kiss"), "/images/opt/forehead-kiss.jpeg"],
  stairs: [opt("stairs"), "/images/opt/stairs.jpeg"],
  sv: [opt("sv"), "/images/opt/sv.jpeg"],
  portraitStanding: opt("portrait-standing"),
  // Not uploaded yet: falls back to the raw file, then to a real photo.
  portraitClose: [opt("portrait-close"), "/images/portrait-close.jpg", opt("couple-main")],
  bwLove: opt("bw-love"),
  shivBlessing: opt("shiv-blessing"),
  loveStory: opt("love-story"),
  venue: [opt("venue"), "/images/venue.jpg", opt("palace-bg")],
  mapPreview: [opt("map-preview"), "/images/map-preview.png"],

  ganesh: opt("ganesh-line"),
  lotus: opt("lotus"),
  floral: opt("floral-bottom"),
  shivParvati: opt("shiv-parvati-gold"),
  palace: opt("palace-bg"),
} satisfies Record<string, ImageSource>;
